# هذه هي منصات نماذج التمويل والدعم المالي المدعومة للمستودع

github: # يمكنك وضع حتى 4 أسماء مستخدمين مفعلين في نظام GitHub Sponsors مثل: [user1, user2]
patreon: # ضع هنا اسم مستخدم واحد الخاص بمنصة باتريون (Patreon)
open_collective: # ضع هنا اسم مستخدم واحد الخاص بمنصة Open Collective
ko_fi: neoxrjs # الحساب الحالي المرتبط بالدعم عبر منصة Ko-fi
