export const models = {
   users: {
      lid: null,
      afk: -1,
      afkReason: '',
      afkObj: {},
      banned: false,
      ban_temporary: 0,
      ban_times: 0,
      premium: false,
      expired: 0,
      lastseen: 0,
      hit: 0,
      warning: 0,
      example: []
   },
   groups: {
      activity: 0,
      antidelete: true,
      antilink: false,
      antivirtex: false,
      antitagsw: true,
      filter: false,
      left: false,
      localonly: false,
      mute: false,
      viewonce: true,
      autosticker: true,
      member: {},
      text_left: '',
      text_welcome: '',
      welcome: true,
      expired: 0,
      stay: false
   },
   chats: {
      chat: 0,
      lastchat: 0,
      lastseen: 0
   },
   setting: {
      autobackup: false,
      autodownload: true,
      antispam: true,
      debug: false,
      notifier: false,
      error: [],
      hidden: [],
      pluginDisable: [],
      receiver: [],
      groupmode: false,
      sk_pack: 'Choso | In Bot',
      sk_author: '© DEV ABOODI OFFICIAL',
      self: false,
      noprefix: false,
      multiprefix: true,
      prefix: ['.', '#', '!', '/'],
      toxic: ["منيوك", "كسمك", "شرموط", "شرموطة", "متناك", "عرص", "لوطب", "قحبة", "قنيط", "منيوكه", "متناكه", "كسم", "كلب", "حمار", "يا بن الحرام", "fuck", "bitch", "asshole"],
      online: true,
      onlyprefix: '+',
      owners: ['249112727808'],
      lastReset: new Date * 1,
      msg: 'مرحباً +tag 🪸\nأنا نظام آلي متكامل (WhatsApp Bot) مصمم لمساعدتك في تنفيذ المهام، البحث، وجلب البيانات والمعلومات المتنوعة مباشرة عبر الواتساب.\n\n◦ *الوضع البرمجي* : +module\n◦ *التخزين الحالي* : +db\n◦ *المكتبة المشغلة* : Baileys +version\n\nإذا واجهت أي مشكلة أو أردت الاشتراك في الميزات المدفوعة، يرجى التواصل مع مطور البوت.',
      style: 4,
      cover: 'https://imgkub.com/images/2025/09/24/image0fe254c6cbb0910a.jpg',
      link: 'https://github.com/dev-ABOODI-cpu/-' // تم ربط البوت بمستودعك الجديد هنا
   }
}

export const structure = { users: [], chats: [], groups: [], instance: [], statistic: {}, sticker: {}, setting: {} }
